name: coffea
description: Create and manage your brews

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_modular: ^6.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  multiselect_formfield: ^0.1.7
  path_provider: ^2.0.15
  provider: ^6.0.2
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/application/assets/coffea-data.json
